name: merge
services:
  cuda:
    container_name: cuda
    volumes:
      - ./:/data
      - C:\Users\zen\Github\MultimediaProcessingPipeline\test:/videos
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    image: zhangyiming748/merge
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility