name: whisper_with_cuda
services:
  cuda:
    container_name: cuda
    volumes:
      - ./:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    image: whisper:cuda
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    tty: true
    stdin_open: true